'use client';

import { useMemo, useState } from 'react';
import { CheckCircle2, Download, FileCheck2, FileSpreadsheet, Search, ShieldCheck, XCircle } from 'lucide-react';
import { createDigitalRequest, decideDigitalRequest, lookupPayroll } from '../../lib/agreserge-client';

const SHEET_URL = 'https://docs.google.com/spreadsheets/d/11R2hU9IzD55MBa8FivztC38boeQAxGpoMly_3yH0Ajk/edit?usp=sharing';
const cop = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value || 0);

export function NominaComprobantes({ session }: any) {
  const [documento, setDocumento] = useState('');
  const [payroll, setPayroll] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const canManage = ['Administrador de Sistemas','Coordinadora Administrativa y Financiera','Coordinador General','Gerente'].includes(session.rol);

  const buscar = async () => {
    setLoading(true); setError(''); setPayroll(null);
    try { const result = await lookupPayroll(documento); setPayroll(result.payroll); }
    catch (e: any) { setError(e.message); }
    finally { setLoading(false); }
  };
  const imprimir = () => {
    if (!payroll) return;
    const windowRef = window.open('', '_blank', 'width=900,height=900');
    if (!windowRef) return alert('Permite ventanas emergentes para generar el comprobante.');
    const deductions = payroll.salud + payroll.pension + payroll.arl + payroll.retencion + payroll.otrosDescuentos;
    windowRef.document.write(`<!doctype html><html><head><title>Comprobante ${payroll.documento}</title><style>body{font-family:Arial;margin:40px;color:#14213d}.head{display:flex;justify-content:space-between;border-bottom:4px solid #1261a0;padding-bottom:18px}.brand{font-size:25px;font-weight:800}.tag{color:#1261a0;text-transform:uppercase;font-weight:700}.box{border:1px solid #dbe4ee;border-radius:14px;padding:18px;margin-top:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row{display:flex;justify-content:space-between;padding:9px;border-bottom:1px solid #edf2f7}.total{background:#eaf4ff;font-size:20px;font-weight:800}.sig{margin-top:70px;display:grid;grid-template-columns:1fr 1fr;gap:60px}.line{border-top:1px solid #111;padding-top:8px;text-align:center}@media print{button{display:none}}</style></head><body><div class="head"><div><div class="tag">Portal institucional</div><div class="brand">AGRESERGE</div></div><div><b>COMPROBANTE DE COMPENSACIÓN</b><br>${new Date().toLocaleDateString('es-CO')}</div></div><div class="box grid"><div><b>Afiliado partícipe</b><br>${payroll.nombre}</div><div><b>Documento</b><br>${payroll.documento}</div><div><b>Cargo / proceso</b><br>${payroll.cargo}</div><div><b>Área</b><br>${payroll.area}</div><div><b>Días compensados</b><br>${payroll.dias}</div></div><div class="box"><h3>Compensaciones</h3><div class="row"><span>Ordinaria</span><b>${cop(payroll.ordinaria)}</b></div><div class="row"><span>Otras compensaciones</span><b>${cop(payroll.otras)}</b></div><div class="row"><span>Transporte</span><b>${cop(payroll.transporte)}</b></div><div class="row"><span>Adicionales</span><b>${cop(payroll.adicionales)}</b></div><h3>Deducciones</h3><div class="row"><span>Salud</span><b>${cop(payroll.salud)}</b></div><div class="row"><span>Pensión</span><b>${cop(payroll.pension)}</b></div><div class="row"><span>ARL</span><b>${cop(payroll.arl)}</b></div><div class="row"><span>Retención y otros descuentos</span><b>${cop(payroll.retencion + payroll.otrosDescuentos)}</b></div><div class="row total"><span>Total recibido</span><b>${cop(payroll.totalRecibido)}</b></div></div><div class="sig"><div class="line">Coordinación administrativa</div><div class="line">Firma digital afiliado partícipe</div></div><p style="margin-top:45px;font-size:11px;color:#5b6777">Generado electrónicamente desde el Portal AGRESERGE. Fuente: FORMATO NOMINA HGC. Deducciones registradas: ${cop(deductions)}.</p><script>window.onload=()=>window.print()</script></body></html>`);
    windowRef.document.close();
  };

  return <div className="grid">
    <div className="welcomeCard span12"><div><span className="welcomeTag">Nómina integrada</span><h2>Centro de nómina y comprobantes</h2><p>Consulta la hoja institucional en línea y genera comprobantes individuales directamente por documento.</p></div><div className="welcomeLogo"><FileSpreadsheet size={54}/></div></div>
    {canManage&&<div className="card span12"><div className="row between"><div><h3>Nómina HGC en línea</h3><p className="muted">La coordinadora mantiene los cálculos en Google Sheets; el portal consulta siempre la versión vigente.</p></div><a className="btn primary" href={SHEET_URL} target="_blank">Abrir hoja completa</a></div><iframe className="sheetFrame" src={`${SHEET_URL.replace('/edit?usp=sharing','/preview')}`}/></div>}
    <div className="card span4"><h3><Search size={19}/> Buscar comprobante</h3><div className="field"><label>Número de documento</label><input className="input" inputMode="numeric" value={documento} onChange={e=>setDocumento(e.target.value.replace(/\D/g,''))} placeholder="Ej. 1112623101"/></div><button className="btn primary" disabled={loading||!documento} onClick={buscar}>{loading?'Consultando nómina...':'Consultar en línea'}</button>{error&&<p className="obsBox">{error}</p>}<p className="mini"><ShieldCheck size={13}/> Consulta protegida por sesión y trazabilidad.</p></div>
    <div className="card span8">{!payroll?<div className="emptyPayroll"><FileCheck2 size={48}/><h3>Comprobante digital</h3><p>Busca un documento para previsualizar el comprobante.</p></div>:<div className="payrollSlip"><div className="row between"><div><span className="welcomeTag">Comprobante de compensación</span><h2>{payroll.nombre}</h2><p>{payroll.documento} · {payroll.cargo} · {payroll.area}</p></div><button className="btn primary" onClick={imprimir}><Download size={15}/> Generar PDF / imprimir</button></div><div className="payrollColumns"><div><h4>Compensaciones</h4><Money label="Ordinaria" value={payroll.ordinaria}/><Money label="Otras" value={payroll.otras}/><Money label="Transporte" value={payroll.transporte}/><Money label="Adicionales" value={payroll.adicionales}/></div><div><h4>Deducciones</h4><Money label="Salud" value={payroll.salud}/><Money label="Pensión" value={payroll.pension}/><Money label="ARL" value={payroll.arl}/><Money label="Retención / otros" value={payroll.retencion+payroll.otrosDescuentos}/></div></div><div className="payrollTotal"><span>Total recibido</span><b>{cop(payroll.totalRecibido)}</b></div></div>}</div>
  </div>;
}

function Money({label,value}:any){return <div className="moneyRow"><span>{label}</span><b>{cop(value)}</b></div>}

export function SolicitudesFirmas({ session, db, setDb }: any) {
  const [tipo,setTipo]=useState('Solicitud de permiso');
  const [form,setForm]=useState<any>({fechaSolicitud:new Date().toISOString().slice(0,10),motivo:'Ausencia personal'});
  const [loading,setLoading]=useState(false);
  const parsed = (value:any)=>{try{return JSON.parse(value||'{}')}catch{return {detalle:value}}};
  const inbox=useMemo(()=> (db.tramites||[]).filter((item:any)=>['Solicitud de permiso','Cambio de turno','Solicitud de viáticos'].includes(item.tipo)).filter((item:any)=>{const meta=parsed(item.observacion);if(session.rol==='Agremiado')return item.agremiadoId===session.id;if(session.rol==='Líder Institucional')return meta.liderId===session.id;return true}),[db.tramites,session]);
  const sync=(payload:any)=>{if(payload.db){setDb(payload.db);localStorage.setItem('portal_agreserge_db_v31',JSON.stringify(payload.db))}};
  const enviar=async()=>{setLoading(true);try{const payload=await createDigitalRequest(tipo,{...form,area:session.areaId,cargo:session.cargo,entidad:session.entidadId});sync(payload);alert('Solicitud radicada y firmada digitalmente.')}catch(e:any){alert(e.message)}finally{setLoading(false)}};
  const decidir=async(id:string,action:string)=>{const comentario=prompt('Comentario de la decisión (opcional)','')||'';try{sync(await decideDigitalRequest(id,action,comentario))}catch(e:any){alert(e.message)}};
  return <div className="grid"><div className="welcomeCard span12"><div><span className="welcomeTag">Flujo sin papel</span><h2>Solicitudes, aprobaciones y firma digital</h2><p>El afiliado radica; el líder aprueba; coordinación administrativa o asistencial revisa y finaliza.</p></div><div className="welcomeLogo"><ShieldCheck size={54}/></div></div>
    <div className="card span4"><h3>Nueva solicitud</h3><div className="field"><label>Tipo</label><select value={tipo} onChange={e=>setTipo(e.target.value)}><option>Solicitud de permiso</option><option>Cambio de turno</option><option>Solicitud de viáticos</option></select></div><div className="field"><label>Fecha de solicitud</label><input className="input" type="date" value={form.fechaSolicitud} onChange={e=>setForm({...form,fechaSolicitud:e.target.value})}/></div>{tipo==='Solicitud de permiso'&&<><div className="field"><label>Motivo</label><select value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})}><option>Ausencia personal</option><option>Cita médica</option><option>Calamidad doméstica</option><option>Capacitación</option><option>Compensatorio</option></select></div><DatePair form={form} setForm={setForm} a="fechaSalida" b="fechaRegreso"/></>}{tipo==='Cambio de turno'&&<><div className="field"><label>Documento de quien acepta</label><input className="input" onChange={e=>setForm({...form,documentoAcepta:e.target.value})}/></div><div className="field"><label>Turno solicitado</label><select onChange={e=>setForm({...form,turno:e.target.value})}><option>Completo</option><option>Mañana</option><option>Tarde</option><option>Noche</option></select></div><DatePair form={form} setForm={setForm} a="fechaCobertura" b="fechaDevolucion"/></>}{tipo==='Solicitud de viáticos'&&<><div className="field"><label>Destino</label><input className="input" onChange={e=>setForm({...form,destino:e.target.value})}/></div><div className="field"><label>Objeto del viaje</label><textarea className="input" rows={3} onChange={e=>setForm({...form,objeto:e.target.value})}/></div><DatePair form={form} setForm={setForm} a="fechaSalida" b="fechaRegreso"/><div className="field"><label>Valor estimado</label><input className="input" type="number" onChange={e=>setForm({...form,valor:Number(e.target.value)})}/></div></>}<div className="field"><label>Observación</label><textarea className="input" rows={3} onChange={e=>setForm({...form,detalle:e.target.value})}/></div><label className="check"><input type="checkbox" required checked={Boolean(form.aceptaFirma)} onChange={e=>setForm({...form,aceptaFirma:e.target.checked})}/> Acepto firmar electrónicamente esta solicitud</label><button className="btn primary" disabled={loading||!form.aceptaFirma} onClick={enviar}>{loading?'Radicando...':'Radicar y firmar'}</button></div>
    <div className="card span8"><h3>Bandeja de solicitudes</h3><div className="requestList">{inbox.length===0&&<p className="muted">No hay solicitudes para este perfil.</p>}{inbox.map((item:any)=>{const meta=parsed(item.observacion);const canDecide=session.rol!=='Agremiado';return <article className="requestCard" key={item.id}><div className="row between"><div><span className="pill rev">{item.estado}</span><h4>{item.tipo}</h4><p>{meta.solicitanteNombre||'Afiliado partícipe'} · {meta.fechaSolicitud||item.generado}</p></div><ShieldCheck size={25}/></div><div className="requestMeta"><span><b>Motivo/destino:</b> {meta.motivo||meta.destino||meta.objeto||'No aplica'}</span><span><b>Fechas:</b> {meta.fechaSalida||meta.fechaCobertura||'-'} → {meta.fechaRegreso||meta.fechaDevolucion||'-'}</span></div><details><summary>Ver trazabilidad y firmas</summary>{(meta.historial||[]).map((h:any,i:number)=><p className="mini" key={i}>✓ {h.estado} · {h.nombre} · {new Date(h.fecha).toLocaleString()} · firma {String(h.firma).slice(0,12)}…</p>)}</details>{canDecide&&item.estado!=='Finalizado'&&item.estado!=='Rechazado'&&<div className="row"><button className="btn primary" onClick={()=>decidir(item.id,item.estado==='Aprobado por líder'?'finalize':'approve')}><CheckCircle2 size={14}/> {item.estado==='Aprobado por líder'?'Finalizar':'Aprobar y firmar'}</button><button className="btn" onClick={()=>decidir(item.id,'reject')}><XCircle size={14}/> Rechazar</button></div>}</article>})}</div></div>
  </div>;
}

function DatePair({form,setForm,a,b}:any){return <div className="row"><div className="field"><label>Desde</label><input className="input" type="date" value={form[a]||''} onChange={e=>setForm({...form,[a]:e.target.value})}/></div><div className="field"><label>Hasta</label><input className="input" type="date" value={form[b]||''} onChange={e=>setForm({...form,[b]:e.target.value})}/></div></div>}
