"use client";
import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Download, Search, Sparkles } from "lucide-react";
import styles from "./talent-interviews.module.css";

const questions = [
  ["graduationDate", "¿Cuándo se graduó?"], ["educationMotivation", "¿Qué le motivó o por qué escogió esa profesión?"],
  ["ruralService", "¿Realizó servicio social obligatorio (rural)?"], ["workExperience", "¿Cuáles han sido sus experiencias laborales?"],
  ["withdrawalReasons", "¿Por qué se retiró de sus empleos anteriores? Describa permanencia, cantidad de trabajos y motivos."],
  ["civilAndChildren", "Estado civil e hijos: ¿tiene hijos?, ¿qué hacen y a qué se dedican?"], ["livesWith", "¿Con quién vive actualmente?"],
  ["familyGroup", "Grupo familiar (padre, madre, hermanos): ¿qué hacen y a qué se dedican?"],
  ["futureExpectations", "¿Qué expectativas laborales y personales tiene a futuro?"], ["personalPhrase", "Escriba una frase que le defina como persona."],
] as const;
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]||c);

export function TalentInterviews(){
  const [rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(""),[entity,setEntity]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function load(){setBusy(true);setError("");const r=await fetch("/api/agreserge-talent-interviews",{cache:"no-store"});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"No se pudo cargar");setRows(d.candidates||[]);setSelected((current:any)=>current?(d.candidates||[]).find((x:any)=>x.id===current.id)||null:current)}
  useEffect(()=>{void load()},[]);
  const entities=useMemo(()=>[...new Set(rows.map(x=>x.entidad_nombre).filter(Boolean))],[rows]);
  const filtered=rows.filter(x=>(!entity||x.entidad_nombre===entity)&&(!status||(x.interview?.status||"PENDIENTE")===status)&&(!query||`${x.nombre_completo} ${x.documento} ${x.area_nombre}`.toLowerCase().includes(query.toLowerCase())));
  const completed=rows.filter(x=>x.interview?.status==="FINALIZADA").length,drafts=rows.filter(x=>x.interview?.status==="BORRADOR").length;
  const stage=selected?.interview?.status||"PENDIENTE",submitted=["ENTREVISTA_ENVIADA","FINALIZADA"].includes(stage),finalized=stage==="FINALIZADA";
  function select(row:any){setSelected({...row,interview:row.interview||{responses:{},status:"PENDIENTE",interview_date:new Date().toISOString().slice(0,10),hr_conclusion:"",automatic_analysis:""}})}
  function updateResponse(key:string,value:string){setSelected((current:any)=>({...current,interview:{...current.interview,responses:{...(current.interview?.responses||{}),[key]:value}}}))}
  async function save(action:"draft"|"submit"|"finalize"){if(!selected)return;setBusy(true);const r=await fetch("/api/agreserge-talent-interviews",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({assessmentId:selected.id,responses:selected.interview.responses,conclusion:selected.interview.hr_conclusion,interviewDate:selected.interview.interview_date,action})});const d=await r.json();setBusy(false);if(!r.ok)return alert(d.error||"No se pudo guardar");await load();alert(action==="finalize"?"Conclusión guardada. El proceso quedó finalizado.":action==="submit"?"Entrevista enviada. Ya puedes agregar la conclusión de Talento Humano.":"Borrador de entrevista guardado.")}
  function print(){if(!selected)return;const i=selected.interview||{},responses=i.responses||{},answerRows=questions.map(([key,label])=>`<tr><th>${esc(label)}</th><td>${esc(responses[key]||"Sin respuesta")}</td></tr>`).join(""),w=window.open("","_blank");if(!w)return;w.document.write(`<!doctype html><html><head><title>Entrevista - ${esc(selected.nombre_completo)}</title><style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Arial;color:#10213b;margin:0}.head{display:flex;align-items:center;gap:18px;border-top:9px solid #0b4ea2;border-bottom:2px solid #dbe7f5;padding:15px 0}.head img{width:68px}.head h1{margin:4px 0;color:#0b4ea2}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:15px 0}.box,.note{padding:10px;border:1px solid #cbdced;border-radius:9px}.title{padding:9px 12px;background:#0b4ea2;color:#fff;font-size:16px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:9px;border:1px solid #dbe7f5;text-align:left;vertical-align:top}th{width:38%;background:#f4f8fd}.note{min-height:75px;font-size:11px;line-height:1.5}.warn{padding:9px;border:1px solid #fed7aa;background:#fff7ed;color:#9a3412;font-size:9px}.footer{margin-top:25px;padding-top:10px;border-top:1px solid;font-size:10px;color:#64748b}</style></head><body><div class="head"><img src="${location.origin}/logo.png"><div><small>ASOCIACIÓN GREMIAL SINDICAL DE PRESTACIONES DE SERVICIOS GENERALES Y DE SALUD DEL VALLE</small><h1>ENTREVISTA DE TALENTO HUMANO</h1></div></div><div class="grid"><div class="box"><b>Afiliado partícipe</b><br>${esc(selected.nombre_completo)}</div><div class="box"><b>Identificación</b><br>${esc(selected.documento)}</div><div class="box"><b>Hospital o entidad</b><br>${esc(selected.entidad_nombre||"")}</div><div class="box"><b>Área o servicio</b><br>${esc(selected.area_nombre||"")}</div><div class="box"><b>Fecha</b><br>${esc(i.interview_date||"")}</div><div class="box"><b>Estado</b><br>${esc(i.status||"PENDIENTE")}</div></div><h2 class="title">Registro de entrevista</h2><table>${answerRows}</table><h2 class="title">Síntesis automatizada</h2><div class="note">${esc(i.automatic_analysis||"Pendiente de envío")}</div><h2 class="title">Conclusión de Talento Humano</h2><div class="note">${esc(i.hr_conclusion||"Pendiente")}</div><p class="warn">La síntesis automática no reemplaza el criterio profesional ni constituye diagnóstico clínico.</p><div class="footer">Generado el ${new Date().toLocaleString("es-CO")}<br><br>____________________________________<br>Firma del profesional de Talento Humano</div><script>window.onload=()=>setTimeout(()=>window.print(),500)<\/script></body></html>`);w.document.close()}
  return <div className={styles.wrap}>
    <section className={styles.hero}><div><span>Etapa posterior a la prueba psicológica</span><h2>Entrevistas de Talento Humano</h2><p>Primero se diligencia y envía la entrevista; luego se registra la conclusión profesional.</p></div><ClipboardList size={56}/></section>
    <section className={styles.kpis}><div><b>{rows.length}</b><span>Habilitados</span></div><div><b>{drafts}</b><span>Borradores</span></div><div><b>{completed}</b><span>Finalizadas</span></div></section>
    <section className={styles.toolbar}><label><Search size={18}/><input placeholder="Nombre, cédula o área" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Todos los hospitales</option>{entities.map(x=><option key={String(x)}>{String(x)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option><option>PENDIENTE</option><option>BORRADOR</option><option>ENTREVISTA_ENVIADA</option><option>FINALIZADA</option></select></section>
    {error&&<p className={styles.error}>{error}</p>}
    <section className={styles.content}><div className={styles.list}>{busy&&<p>Cargando…</p>}{filtered.map(x=><button key={x.id} className={selected?.id===x.id?styles.active:""} onClick={()=>select(x)}><span><b>{x.nombre_completo}</b><small>{x.documento} · {x.entidad_nombre} · {x.area_nombre}</small></span><em>{x.interview?.status||"PENDIENTE"}</em></button>)}</div>
      <div className={styles.detail}>{!selected?<div className={styles.empty}><ClipboardList/><b>Selecciona un agremiado</b><span>Solo aparecen personas que finalizaron la prueba psicológica.</span></div>:<><div className={styles.detailHead}><div><span className={styles.pill}>{stage}</span><h3>{selected.nombre_completo}</h3><p>{selected.documento} · {selected.entidad_nombre} · {selected.area_nombre}</p></div><button onClick={print}><Download size={18}/> PDF / imprimir</button></div>
        <div className={styles.steps}><b className={submitted?styles.done:styles.current}>1. Diligenciar y enviar entrevista</b><b className={submitted?styles.current:styles.locked}>2. Agregar conclusión</b></div>
        <div className={styles.form}><label className={styles.field}>Fecha de entrevista<input disabled={submitted} type="date" value={selected.interview?.interview_date||""} onChange={e=>setSelected({...selected,interview:{...selected.interview,interview_date:e.target.value}})}/></label><label className={styles.field}>Prueba psicológica finalizada<input disabled value={selected.completed_at?new Date(selected.completed_at).toLocaleDateString("es-CO"):"Sí"}/></label>
          {questions.map(([key,label])=><label key={key} className={`${styles.field} ${["workExperience","withdrawalReasons","familyGroup"].includes(key)?styles.wide:""}`}>{label}<textarea disabled={submitted} value={selected.interview?.responses?.[key]||""} onChange={e=>updateResponse(key,e.target.value)}/></label>)}
          {submitted?<><article className={styles.analysis}><header><Sparkles size={19}/> Síntesis automática de apoyo</header><p>{selected.interview?.automatic_analysis}</p></article><label className={`${styles.field} ${styles.wide}`}>Conclusión y concepto de Talento Humano<textarea disabled={finalized} value={selected.interview?.hr_conclusion||""} onChange={e=>setSelected({...selected,interview:{...selected.interview,hr_conclusion:e.target.value}})}/></label><p className={styles.notice}>La conclusión final siempre corresponde al profesional responsable de Talento Humano.</p></>:<article className={`${styles.analysis} ${styles.disabled}`}><header><Sparkles size={19}/> Síntesis y conclusión bloqueadas</header><p>Primero completa y envía la entrevista. Después se habilitarán la síntesis y el concepto de Talento Humano.</p></article>}
          <div className={styles.actions}>{!submitted&&<><button onClick={()=>save("draft")} disabled={busy}>Guardar borrador</button><button className={styles.primary} onClick={()=>save("submit")} disabled={busy}>Enviar entrevista</button></>}{submitted&&!finalized&&<button className={styles.primary} onClick={()=>save("finalize")} disabled={busy}>Guardar conclusión y finalizar</button>}{finalized&&<b>Proceso finalizado y protegido.</b>}</div>
        </div></>}</div></section>
  </div>
}
