export const administrativeDocumentRequirements = [
  "Copia de cédula de ciudadanía al 150% a color",
  "Foto para el carnet fondo blanco digital",
  "Libreta militar al 150% a color o constancia del Ministerio de Prestación del Servicio (excepto hombres mayores de 50 años)",
  "Formato único de hoja de vida de Función Pública totalmente diligenciado y firmado",
  "Diploma de grado (bachiller, pregrado y postgrado) de los estudios realizados",
  "Acta de grado (bachiller, pregrado y postgrado) de los estudios realizados",
  "Tarjeta profesional",
  "RUT - Registro Único Tributario con fecha actual",
  "Declaración juramentada de bienes y rentas de ingreso diligenciada y firmada - formato único de Función Pública",
  "Certificado de antecedentes judiciales - Policía Nacional",
  "Certificado de antecedentes fiscales - Contraloría General de la Nación",
  "Certificado de antecedentes disciplinarios - Procuraduría General de la Nación",
  "Certificado de medidas correctivas - Policía Nacional",
  "Certificado de inhabilidades de delitos sexuales - Policía Nacional",
  "Certificado de no figuración en el Registro de Deudores Alimentarios Morosos (REDAM)",
  "Certificaciones laborales (mínimo 2)",
  "Manifestación para retención en la fuente - formato AGRESERGE",
  "Acuerdo de uso adecuado de recursos institucionales - formato AGRESERGE",
  "Autorización para el tratamiento de datos personales - formato AGRESERGE",
  "Compromiso de confidencialidad y no divulgación de la información - formato AGRESERGE",
  "Dependiente económico diligenciado y firmado",
  "Carnet de vacunas: Hepatitis B, Influenza, Tétano y Difteria, Triple viral",
  "Examen médico laboral de ingreso (vigencia no mayor a 2 años)",
  "Certificación bancaria (vigencia no mayor a 30 días)",
  "Certificación EPS (vigencia no mayor a 30 días)",
  "Certificación de afiliación al fondo de pensiones (vigencia no mayor a 30 días)",
  "Certificación de afiliación a la ARL",
  "Certificado de afiliación a caja de compensación",
] as const;

export const healthcareDocumentRequirements = [
  "Copia de cédula de ciudadanía al 150% a color",
  "Foto para el carnet fondo blanco digital",
  "Libreta militar al 150% a color o constancia del Ministerio de Prestación del Servicio (excepto hombres mayores de 50 años)",
  "Formato único de hoja de vida de Función Pública totalmente diligenciado y firmado",
  "Diploma de grado (bachiller, pregrado y postgrado) de los estudios realizados",
  "Acta de grado (bachiller, pregrado y postgrado) de los estudios realizados",
  "Resolución de convalidación de títulos (si los estudios fueron realizados en el exterior)",
  "Tarjeta profesional",
  "RETHUS con fecha actual",
  "Póliza de responsabilidad civil vigente ($500.000.000 profesionales / $150.000.000 técnicos)",
  "Cursos y soportes documentales exigidos para el servicio (vigencia máxima 2 años)",
  "RUT - Registro Único Tributario con fecha actual",
  "Declaración juramentada de bienes y rentas de ingreso diligenciada y firmada - formato único de Función Pública",
  "Certificado de antecedentes judiciales - Policía Nacional",
  "Certificado de antecedentes fiscales - Contraloría General de la Nación",
  "Certificado de antecedentes disciplinarios - Procuraduría General de la Nación",
  "Certificado de medidas correctivas - Policía Nacional",
  "Certificado de inhabilidades de delitos sexuales - Policía Nacional",
  "Certificado de no figuración en el Registro de Deudores Alimentarios Morosos (REDAM)",
  "Certificaciones laborales (mínimo 2)",
  "Manifestación para retención en la fuente - formato AGRESERGE",
  "Acuerdo de uso adecuado de recursos institucionales - formato AGRESERGE",
  "Autorización para el tratamiento de datos personales - formato AGRESERGE",
  "Compromiso de confidencialidad y no divulgación de la información - formato AGRESERGE",
  "Dependiente económico diligenciado y firmado - formato AGRESERGE",
  "Carnet de vacunas: Hepatitis A y B, Influenza, Tétano y Difteria, Triple viral, Varicela",
  "Examen médico laboral de ingreso (vigencia no mayor a 2 años)",
  "Certificación bancaria (vigencia no mayor a 30 días)",
  "Certificación EPS (vigencia no mayor a 30 días)",
  "Certificación de afiliación al fondo de pensiones (vigencia no mayor a 30 días)",
  "Certificación de afiliación a la ARL",
  "Certificado de afiliación a caja de compensación",
] as const;

export const healthcareCourseDetails = [
  "Gestión del duelo: enfermería, auxiliares de enfermería y medicina",
  "Cuidado del donante: medicina",
  "Manejo del dolor y cuidado paliativo: medicina",
  "Víctimas de violencia sexual: talento humano de urgencias, hospitalización, consulta externa, nutrición, psicología, trabajo social, promoción y mantenimiento, vacunación y odontología",
  "Ataques con agentes químicos: enfermería, auxiliares de enfermería y medicina",
  "Administración de inmunobiológicos: personal que administra vacunas",
  "Toma de muestras de cuello uterino y ginecológicas: personal que toma citologías",
  "Soporte vital básico: auxiliares de enfermería",
  "Soporte vital avanzado: medicina y enfermería",
  "Curso virtual certificado de defunción: medicina",
  "Licencia de conducción B1 y primeros auxilios o primer respondiente: conductores de ambulancia",
  "VigiFlow: regencia de farmacia",
] as const;

export function documentRequirements(tipo?: string) {
  return tipo === "Administrativo"
    ? [...administrativeDocumentRequirements]
    : [...healthcareDocumentRequirements];
}
