export const psychologyQuestions: string[] = [
  "Me dejo llevar por los demás",
  "Me disgustan las obras de ficción",
  "Me desanimo con facilidad",
  "No me gusta involucrarme en los problemas de los demás",
  "Lloro durante las películas",
  "Me encanta soñar despierto",
  "No rehúso hablar de mí mismo",
  "Intento seguir las reglas",
  "Quiero que me dejen en paz",
  "Hago cosas que otros encuentran extrañas",
  "Respeto la autoridad",
  "No respeto las reglas",
  "Hago cosas inesperadas",
  "Me enfado con facilidad",
  "Tengo cambios de humor radicales con frecuencia",
  "Me hago cargo",
  "Me siento culpable cuando digo \"no\"",
  "Supero las adversidades con facilidad",
  "No me interesan las argumentaciones y conversaciones teóricas",
  "Busco el silencio",
  "Animo a la gente",
  "Rara vez me pierdo en mis pensamientos",
  "No hablo en presencia de extraños",
  "Nado a contra corriente",
  "No me importa comer sólo",
  "Intento no pensar en los necesitados",
  "Digo lo que pienso",
  "Me encantan las grandes fiestas",
  "Siempre estoy de broma",
  "Me opongo a la autoridad",
  "Creo en la importancia del arte",
  "Hago amigos con facilidad",
  "Nunca me involucro en desafíos",
  "Me intereso por la vida de los demás",
  "Pospongo tareas desagradables",
  "Raramente le busco un significado más profundo a las cosas",
  "No me gustan los acontecimientos con mucha gente",
  "Empleo tacos",
  "Disfruto dejando volar mi imaginación",
  "Me siento amenazado con facilidad",
  "Siento las emociones de los demás",
  "Sé evadir las reglas",
  "Aprendo rápidamente",
  "Me disgusta la música alta",
  "No me gustan las películas de acción",
  "Me resisto a la autoridad",
  "No me gusta la poesía",
  "Creo que la gente básicamente sigue una moralidad",
  "No me molesta el desorden",
  "Me enojan los errores de otros",
  "Me considero una persona normal",
  "Me guardo mis pensamientos",
  "Saco tiempo para los demás",
  "Utilizo mi cerebro",
  "No me enojo con facilidad",
  "Escondo mis sentimientos",
  "Me siento desesperado",
  "Disfruto discutiendo sobre películas y libros con mis amigos",
  "Me gusta perderme en mis pensamientos",
  "Llevo a cabo las tareas de inmediato",
  "Creo que las leyes deberían ser aplicadas estrictamente",
  "Hago que la gente se sienta a gusto",
  "Me preocupo por las cosas",
  "No estoy realmente interesado en los demás",
  "Confío en los demás",
  "No disfruto viendo a actuaciones de danza",
  "Reflexiono antes de actuar",
  "Llevo la conversación a un nivel más elevado",
  "Dejo mis cosas personales al margen",
  "Me disgusto con facilidad",
  "Conozco las respuestas a muchas preguntas",
  "Intento perdonar y olvidar",
  "Me irrito con facilidad",
  "Intento evitar a la gente complicada",
  "Quiero que todo esté \"en su punto\"",
  "Evito argumentaciones y conversaciones filosóficas",
  "Leo mucho",
  "Rara vez sueño despierto",
  "Tengo miedo de hacer lo incorrecto",
  "Disfruto de mi privacidad",
  "Me hieren con facilidad",
  "Exteriorizo mis pensamientos íntimos",
  "No hablo mucho",
  "Me encantan las flores",
  "Creo en una única religión verdadera",
  "Mi vocabulario es pobre",
  "Sopeso los pros y los contras",
  "Me gusta leer",
  "No estoy interesado en ideas abstractas",
  "Exteriorizo mis sentimientos",
  "No confío en la gente",
  "Entretengo a mis amigos",
  "A menudo me siento incómodo rodeado de los demás",
  "Disfruto siendo parte de una multitud ruidosa",
  "No tengo miedo de ser crítico",
  "Sospecho que los demás esconden motivos ocultos",
  "No me gusto a mí mismo",
  "Me fío de lo que la gente dice",
  "Creo que la gente rara vez dice toda la verdad",
  "Me quedo en un segundo plano",
  "Espero que sean otros los que me enseñen el camino",
  "Me encanta idear nuevas formas de hacer las cosas",
  "Rara vez me siento triste",
  "Tengo poco que decir",
  "No me molesto con facilidad",
  "Insisto hasta que todo está perfecto",
  "Tengo una palabra amable para todo el mundo",
  "Actuo de forma descontrolada y alocada",
  "Soy preciso en mi trabajo",
  "Me cuesta acercarme a los demás",
  "No puedo vivir sin la compañía de otras personas",
  "Inivierto tiempo pensando sobre errores pasados",
  "Soy el alma de la fiesta",
  "No me preocupa aquello que ya ha pasado",
  "Me gusta ponerme de pie cuando oigo el himno nacional",
  "Las personas desordenadas no me molestan",
  "Disfruto pasando tiempo sólo",
  "Me gusta el orden",
  "Estoy abierto a los demás",
  "A menudo me siento triste",
  "Recelo de los demás",
  "Hablo con mucha gente distinta en las fiestas",
  "Quiero estar a cargo",
  "Contrarresto los argumentos de los demás",
  "Raramente advierto mis reacciones emocionales",
  "Sé cómo consolar a los demás",
  "No me importa ser el centro de atención",
  "Dejo que otros tomen las decisiones",
  "Sé que no soy una persona especial",
  "Hago las cosas siguiendo estrictamente las reglas",
  "Disfruto del silencio",
  "Me salto las palabras complicadas cuando leo",
  "No dejo que los demás me desanimen",
  "Prefiero la variedad a la rutina",
  "No me frustro con facilidad",
  "Disfruto siendo parte de un grupo",
  "Prefiero hacer las cosas por mí mismo",
  "Me siento abatido por las adversidades",
  "Tiendo a juzgar a los demás rápidamente",
  "Adopto posiciones fuera de la norma",
  "Creo que la gente es fundamentalmente malvada",
  "Mi habitación es un desorden",
  "Me cuesta perdonar a los demás",
  "Puedo tomar medidas contundentes",
  "Me siento a gusto conmigo mismo",
  "Disfruto reuniendo/reconciliando a la gente",
  "Tiendo a analizar las cosas",
  "Hago comentarios profundos",
  "Juzgo a la gente por su apariencia",
  "Disfruto del trabajo en equipo",
  "Disfruto escuchando nuevas ideas",
  "Me cuesta que otras personas me conozcan",
  "Me siento confundido con facilidad",
  "Soy el último en reir con un chiste",
  "Creo en las buenas intenciones de los demás",
  "Casi siempre estoy relajado",
  "Tomo el control sobre las cosas",
  "Revelo poco de mí mismo",
  "Empiezo las conversaciones",
  "Me siento cómodo rodeado de gente",
  "Rara vez estoy de broma",
  "Soy una persona abierta sobre mis sentimientos con los demás",
  "No soporto que alguien me contradiga"
];

export const responseLabels = [
  "Totalmente en desacuerdo",
  "En desacuerdo",
  "Ni de acuerdo ni en desacuerdo",
  "De acuerdo",
  "Totalmente de acuerdo",
];

export function responseSummary(responses: number[]) {
  const counts = [1, 2, 3, 4, 5].map((value) => responses.filter((item) => item === value).length);
  const average = responses.length
    ? Number((responses.reduce((total, value) => total + value, 0) / responses.length).toFixed(2))
    : 0;
  return { answered: responses.length, total: psychologyQuestions.length, average, counts };
}
