create table if not exists public.agreserge_profiles (
  user_id text primary key references public.agreserge_users(id) on delete cascade,
  documento text not null unique,
  lugar_expedicion text,
  cnv text,
  fecha_ingreso date,
  fecha_retiro date,
  estado_laboral text,
  formacion text,
  proceso text,
  direccion text,
  barrio text,
  municipio text,
  departamento text,
  sexo text,
  estado_civil text,
  personas_cargo integer,
  fecha_nacimiento date,
  lugar_nacimiento text,
  tipo_contrato text,
  forma_pago text,
  banco text,
  tipo_cuenta text,
  numero_cuenta text,
  eps text,
  afp text,
  arl text,
  caja_compensacion text,
  rh text,
  talla text,
  retencion_fuente text,
  observaciones text,
  fecha_examen_medico date,
  ciudad_votacion text,
  puesto_votacion text,
  fuente_origen text,
  datos_adicionales jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agreserge_profiles_estado_idx on public.agreserge_profiles (estado_laboral);
create index if not exists agreserge_profiles_municipio_idx on public.agreserge_profiles (municipio);
alter table public.agreserge_profiles enable row level security;
